export { default as Article } from './Article'
export { default as Edit } from './Edit'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
export { default as Settings } from './Settings'
